version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "06:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    labels: [dependencies, python]
    commit-message:
      prefix: deps
    groups:
      python-development:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "06:30"
      timezone: Europe/London
    open-pull-requests-limit: 10
    labels: [dependencies, github-actions]
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns: ["*"]

